CREATE DATABASE  IF NOT EXISTS companydb;
USE companydb;
CREATE TABLE employee(
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) DEFAULT  NULL,
    salary INT(5) DEFAULT  NULL,
    email VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY(ID)
);